
version: '2'

volumes:
  orderer.loc.com:
  peer0.intel.loc.com:
  peer1.intel.loc.com:
  peer0.lenovo.loc.com:
  peer1.lenovo.loc.com:
  peer0.fedex.loc.com:
  peer1.fedex.loc.com:
  peer0.govregulator.loc.com:
  peer1.govregulator.loc.com:

networks:
  loc:

services:
  ca-intel:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-intel
      - FABRIC_CA_SERVER_TLS_ENABLED-true
      - FABRIC_CA_SERVER_TLS_CERTIFICATE=/etc/hyperledger/fabric-ca-server-config/ca.intel.loc.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/fc76486c2c97e2e298395d1df7a02f0bdbdac0e2b8e8ec969c726e8b9014f3e3_sk
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start -ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.intel.loc.com-cert.pem -ca.keyfile /etc/hyperledger/fabric-ca-server-config/fc76486c2c97e2e298395d1df7a02f0bdbdac0e2b8e8ec969c726e8b9014f3e3_sk -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/intel.loc.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - loc

  ca-lenovo:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-lenovo
      - FABRIC_CA_SERVER_TLS_ENABLED-true
      - FABRIC_CA_SERVER_TLS_CERTIFICATE=/etc/hyperledger/fabric-ca-server-config/ca.lenovo.loc.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/af5b3adddaf1172ee2edd33a239e99d8a57b9d60dda0fa0f2466fa528333407d_sk
    ports:
      - 8054:8054
    command: sh -c 'fabric-ca-server start -ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.lenovo.loc.com-cert.pem -ca.keyfile /etc/hyperledger/fabric-ca-server-config/af5b3adddaf1172ee2edd33a239e99d8a57b9d60dda0fa0f2466fa528333407d_sk -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/lenovo.loc.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - loc


  ca-fedex:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-fedex
      - FABRIC_CA_SERVER_TLS_ENABLED-true
      - FABRIC_CA_SERVER_TLS_CERTIFICATE=/etc/hyperledger/fabric-ca-server-config/ca.fedex.loc.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/e82d3e01044bc70142a3868f26c8b6cd216a503a0781d41af177dcac1eb77c86_sk
    ports:
      - 9054:9054
    command: sh -c 'fabric-ca-server start -ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.fedex.loc.com-cert.pem -ca.keyfile /etc/hyperledger/fabric-ca-server-config/e82d3e01044bc70142a3868f26c8b6cd216a503a0781d41af177dcac1eb77c86_sk -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/fedex.loc.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - loc


  ca-govregulator:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-govregulator
      - FABRIC_CA_SERVER_TLS_ENABLED-true
      - FABRIC_CA_SERVER_TLS_CERTIFICATE=/etc/hyperledger/fabric-ca-server-config/ca.govregulator.loc.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/9c1104d54263b9e9a07cf1ff304d836e5899ad2b1818660a860ddfc3ca9fab9f_sk
    ports:
      - 10054:10054
    command: sh -c 'fabric-ca-server start -ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.govregulator.loc.com-cert.pem -ca.keyfile /etc/hyperledger/fabric-ca-server-config/9c1104d54263b9e9a07cf1ff304d836e5899ad2b1818660a860ddfc3ca9fab9f_sk -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/govregulator.loc.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - loc

  orderer.loc.com:
    extends: 
      file: base/docker-compose-base.yaml
      service: orderer.loc.com
    container_name: orderer.loc.com
    networks:
      - loc

  peer0.intel.loc.com:
    extends: 
      file: base/docker-compose-base.yaml
      service: peer0.intel.loc.com
    container_name: peer0.intel.loc.com
    networks:
      - loc

  peer1.intel.loc.com:
    extends: 
      file: base/docker-compose-base.yaml
      service: peer1.intel.loc.com
    container_name: peer1.intel.loc.com
    networks:
      - loc

  peer0.lenovo.loc.com:
    extends: 
      file: base/docker-compose-base.yaml
      service: peer0.lenovo.loc.com
    container_name: peer0.lenovo.loc.com
    networks:
      - loc

  peer1.lenovo.loc.com:
    extends: 
      file: base/docker-compose-base.yaml
      service: peer1.lenovo.loc.com
    container_name: peer1.lenovo.loc.com
    networks:
      - loc

  peer0.fedex.loc.com:
    extends: 
      file: base/docker-compose-base.yaml
      service: peer0.fedex.loc.com
    container_name: peer0.fedex.loc.com
    networks:
      - loc

  peer1.fedex.loc.com:
    extends: 
      file: base/docker-compose-base.yaml
      service: peer1.fedex.loc.com
    container_name: peer1.fedex.loc.com
    networks:
      - loc

  peer0.govregulator.loc.com:
    extends: 
      file: base/docker-compose-base.yaml
      service: peer0.govregulator.loc.com
    container_name: peer0.govregulator.loc.com
    networks:
      - loc

  peer1.govregulator.loc.com:
    extends: 
      file: base/docker-compose-base.yaml
      service: peer1.govregulator.loc.com
    container_name: peer1.govregulator.loc.com
    networks:
      - loc